# Copyright (2019) Universidad de Granma
#
# This file is part of hddicom project.
#
# hddicom is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# hddicom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with hddicom.  If not, see <http://www.gnu.org/licenses/>.

stages:
 - install
 
install_project_dependencies:
 stage: install
 script:
  - apt-get install python-gdcm
  - apt-get install python3tk
  - python3 -m venv venv
  - pip install -r requeriments
 tags: 
  - install
  

